# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Detects the host CPU count at workspace-fetch time.

Exposes `NUM_CPUS` (int) and a few precomputed ceilings used for sizing
Verilator and Make parallelism so they adapt to the host rather than
being pinned to a single-site number.

Usage:
    load("@coralnpu_host_cpus//:defs.bzl", "NUM_CPUS", "VERILATOR_THREADS", "MAKE_JOBS")
"""

def _host_cpus_impl(repository_ctx):
    nproc = repository_ctx.which("nproc")
    cpus = 4
    if nproc:
        result = repository_ctx.execute([nproc])
        if result.return_code == 0:
            stripped = result.stdout.strip()
            if stripped.isdigit():
                cpus = int(stripped)

    # Verilator past ~8 threads tends to hit scheduling overhead more than
    # it gains speedup on typical designs; cap to keep runtime sane even
    # on big-iron CI hosts, but never above the host's CPU count.
    verilator_threads = min(cpus, 8)

    # Check for explicit user override in environment
    env_jobs = repository_ctx.os.environ.get(
        "CORALNPU_MAKE_JOBS",
        repository_ctx.os.environ.get("MAKE_JOBS", ""),
    )
    if env_jobs.isdigit() and int(env_jobs) > 0:
        make_jobs = int(env_jobs)
    elif cpus <= 4:
        # Leave a core for the OS on small hosts (e.g. 4 -> 3, 2 -> 1)
        make_jobs = max(cpus - 1, 1)
    else:
        # For workstations (e.g. 12 cores -> 10 jobs) and larger hosts, leave 2
        # cores free to ensure desktop responsiveness and avoid system starvation.
        make_jobs = max(cpus - 2, 2)

    repository_ctx.file("BUILD.bazel", content = "")
    repository_ctx.file(
        "defs.bzl",
        content = (
            "# Generated by //rules:host_cpus.bzl\n" +
            "NUM_CPUS = {cpus}\n" +
            "VERILATOR_THREADS = {vthreads}\n" +
            "MAKE_JOBS = {mjobs}\n"
        ).format(
            cpus = cpus,
            vthreads = verilator_threads,
            mjobs = make_jobs,
        ),
    )

host_cpus = repository_rule(
    implementation = _host_cpus_impl,
    doc = "Detects host CPU count and exposes parallelism knobs.",
    environ = [
        "CORALNPU_MAKE_JOBS",
        "MAKE_JOBS",
    ],
    local = True,
)
